In [3]:
%load_ext autoreload
%autoreload 2

import sys, os
sys.path.append("/".join(os.getcwd().split("/")[:-2]) + "/")

In [4]:
from katalogue.insee.communes import DépôtINSEECommunes

dépôt = DépôtINSEECommunes()
communes = dépôt.communes()
communes.sample(5)

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT
6044,COM,17016,75.0,17,17D,171,1,ARCHIAC,Archiac,Archiac,1707,NaN
20506,COM,52201,44.0,52,52D,523,0,FLAMMERECOURT,Flammerécourt,Flammerécourt,5209,NaN
21432,COM,54308,44.0,54,54D,542,0,LEINTREY,Leintrey,Leintrey,5401,NaN
31250,COM,74013,84.0,74,74D,744,1,ANTHY SUR LEMAN,Anthy-sur-Léman,Anthy-sur-Léman,7415,NaN
32432,COM,77131,11.0,77,77D,771,0,COULOMMIERS,Coulommiers,Coulommiers,7705,NaN

In [5]:
from katalogue.datagouv.associations import DépôtDataGouvAssociations

In [7]:
dépôt = DépôtDataGouvAssociations()
assos = dépôt.associations(True)
assos.sample(5)

Lecture sauvegarde existante  /home/laurent/.katalogue/datagouv/locale_DépôtDataGouvAssociations_associations.pkl

,id,titre,objet,objet_social1,objet_social2,date_creat,adrs_codeinsee,adrs_codepostal,titre_court,date_disso,objet_social_parent_id,objet_social_parent_lib,objet_social_lib,objet_social_parent_id_2,objet_social_parent_lib_2,objet_social_lib_2
1953767,W751255950,RALLYE PHENIX,proposer aux enfants des membres des rencontre...,6000.0,11000.0,2020-02-24,75117,75017.0,RALLYE PHENIX,NaT,6000.0,"CULTURE, PRATIQUES D'ACTIVITÉS ARTISTIQUES, PR...","CULTURE, PRATIQUES D'ACTIVITÉS ARTISTIQUES, PR...",11000.0,"SPORTS, ACTIVITÉS DE PLEIN AIR","SPORTS, ACTIVITÉS DE PLEIN AIR"
227836,402P0402005553,DEPARTEMENTALE POUR LE TRANSPORT DES ELEVES DE...,Etudier et poursuivre le transport des eleves ...,NaN,0.0,NaT,40192,40000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
286464,113S0113001496,SIDEROS,En sommeil,6020.0,0.0,NaT,11024,11100,NaN,NaT,6000.0,"CULTURE, PRATIQUES D'ACTIVITÉS ARTISTIQUES, PR...","arts graphiques, bandes dessinées, peinture, s...",NaN,NaN,NaN
2069618,W353003131,ASSOCIATION DE PARENTS D'ELEVES DU CHAT CHEVRE,Diffuser la pensée laïque et défendre les inst...,15010.0,0,1984-01-06,35001.0,35690.0,ASSOCIATION DE PARENTS D'ELEVES DU,NaT,15000.0,ÉDUCATION FORMATION,"organisation de professions enseignantes, amic...",NaN,NaN,NaN
1708598,W883005871,FOUCH'ANIM,"proposer, organiser différentes activités à de...",21020.0,0.0,2021-10-29,88413,88100.0,FOUCH'ANIM,NaT,21000.0,"SERVICES FAMILIAUX, SERVICES AUX PERSONNES ÂGÉES","foyers pour personnes âgées, maisons de retrai...",NaN,NaN,NaN