In [1]:
%load_ext autoreload
%autoreload 2

import sys, os
sys.path.append("/".join(os.getcwd().split("/")[:-2]) + "/")

In [2]:
from katalogue.insee.communes import DépôtINSEECommunes

dépôt = DépôtINSEECommunes()
communes = dépôt.communes()
communes.sample(5)

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT
19244,COM,50207,28.0,50,50D,502,0,GOLLEVILLE,Golleville,Golleville,5004,NaN
36809,COM,89426,27.0,89,89D,891,0,VAL DE MERCY,Val-de-Mercy,Val-de-Mercy,8921,NaN
26962,COM,64107,75.0,64,64D,641,0,BEHORLEGUY,Béhorléguy,Béhorléguy,6412,NaN
25739,COM,62258,32.0,62,62D,621,0,CROISETTE,Croisette,Croisette,6238,NaN
26261,COM,62785,32.0,62,62D,621,0,SAVY BERLETTE,Savy-Berlette,Savy-Berlette,6207,NaN

In [3]:
from katalogue.datagouv.associations import DépôtDataGouvAssociations

In [6]:
dépôt = DépôtDataGouvAssociations()
assos = dépôt.associations(sauvegarder_localement=False)
assos.sample(5)

,id,titre,objet,objet_social1,objet_social2,date_creat,adrs_codeinsee,adrs_codepostal,titre_court,date_disso,objet_social_parent_id,objet_social_parent_lib,objet_social_lib,objet_social_parent_id_2,objet_social_parent_lib_2,objet_social_lib_2
240862,723P0723010429,SECOURS ENFANTS DU TIERS MONDE,Venir en aide aux enfants victimes d'esclavage...,20020.0,0.0,2001-01-16,72500,0,NaN,NaT,20000.0,"ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE A...",associations caritatives intervenant au plan i...,NaN,NaN,NaN
667650,842P0842201292,CLUB TAURIN ORANGEOIS,FAIRE REVIVRE LES TRADITIONNELLES COURSES LIBR...,0.0,0.0,1946-03-10,84087,84100,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1700995,W881003523,ENT'RAID ET PISTONS,récolter des fonds afin de participer au 4L Tr...,20020.0,0.0,2012-05-10,1283,1100.0,ENT'RAID ET PISTONS,2014-11-22,20000.0,"ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE A...",associations caritatives intervenant au plan i...,NaN,NaN,NaN
463930,393S0393001409,LES AMIS DES DEUX PUITS,"Organisation d'activites, d'animation au sein ...",7000.0,9005.0,NaT,39561,39260,NaN,NaT,7000.0,"CLUBS DE LOISIRS, RELATIONS","CLUBS DE LOISIRS, RELATIONS",9000.0,ACTION SOCIOCULTURELLE,"maisons de jeunes, foyers, clubs de jeunes"
588151,9R1P9741004590,ASSOCIATION FRATERNITE DES MUSULMANS REUNIONNA...,Promouvoir le dialogue islamo-chretien et avec...,0.0,0.0,NaT,97411,0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN